apiVersion: v1  # API version
kind: Namespace  # This is a Namespace resource
metadata:
  name: bonita  # Name of the Namespace
# The purpose of this Namespace is to provide an isolated environment within the Kubernetes cluster for bonita application.