# ConfigMap: db-connect-config
# This ConfigMap stores configuration data for the Bonita application, such as database connection information.
apiVersion: v1
data:
  BIZ_DB_NAME: business_data
  BIZ_DB_PASS: bpm
  BIZ_DB_USER: business_data
  DB_HOST: bonita-db
  DB_NAME: bonita
  DB_PASS: bpm
  DB_PORT: "5432"
  DB_USER: bonita
  DB_VENDOR: postgres
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-connect-config
  namespace: bonita
---

# ConfigMap: bonita-custom-init
# This ConfigMap stores a script to set the default logging level to INFO for the Bonita application.
apiVersion: v1
data:
  set_logging_level_to_info.sh: |-
    #!/bin/bash

    # Path to the log4j2 appenders configuration file
    CONFIG_FILE="/opt/bonita/conf/logs/log4j2-appenders.xml"

    # Check if the configuration file exists
    if [ ! -f "$CONFIG_FILE" ]; then
        echo "Configuration file not found: $CONFIG_FILE"
        exit 1
    fi

    # Display a message about checking and setting the log level
    echo "Ensuring root logger level is set to INFO in $CONFIG_FILE..."

    # The script uses sed to process the XML file
    # It targets the Root logger element and changes its level to INFO
    sed -i 's/<Root level="[^"]*"/<Root level="INFO"/' $CONFIG_FILE

    echo "Log level update completed."
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: bonita-custom-init
  namespace: bonita
---

# Secret: db-pwd
# This Secret stores the encoded password for the PostgreSQL database used by Bonita.
apiVersion: v1
data:
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==
kind: Secret
metadata:
  creationTimestamp: null
  name: db-pwd
  namespace: bonita
---

# Secret: bonita-credentials
# This Secret stores encoded credentials for the Bonita Runtime Admin and Platform login.
# Initially, this Secret used TENANT_LOGIN/TENANT_PASSWORD, but a warning in the application log indicated
# these were deprecated. It was updated to use BONITA_RUNTIME_ADMIN_USERNAME/BONITA_RUNTIME_ADMIN_PASSWORD
# as recommended by the application.
apiVersion: v1
data:
  BONITA_RUNTIME_ADMIN_USERNAME: Ym9uaXRhLWxvZ2lu
  BONITA_RUNTIME_ADMIN_PASSWORD: Ym9uaXRhLXB3ZA==
  PLATFORM_LOGIN: cGxhdGZvcm0tbG9naW4=
  PLATFORM_PASSWORD: cGxhdGZvcm0tcHdk
kind: Secret
metadata:
  creationTimestamp: null
  name: bonita-credentials
  namespace: bonita
