# RoleBinding Configuration:
# This RoleBinding binds the 'secret-reader' Role to the 'bonita-service-account' ServiceAccount.
# It grants the permissions defined in the 'secret-reader' Role to the specified ServiceAccount within the 'bonita' namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding  # Name of the RoleBinding
  namespace: bonita  # Namespace where the RoleBinding is applied
subjects:
- kind: ServiceAccount  # Specifies the kind of subject (a ServiceAccount in this case)
  name: bonita-service-account  # The name of the ServiceAccount to bind the role to
  namespace: bonita  # Namespace of the ServiceAccount
roleRef:
  kind: Role  # The kind of role being referenced
  name: secret-reader  # The name of the Role to bind
  apiGroup: rbac.authorization.k8s.io  # API group of the Role