apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding
  namespace: bonita
subjects:
- kind: ServiceAccount
  name: bonita-service-account
  namespace: bonita
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io