apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bonita  # The namespace where the role is applied
  name: secret-reader  # The name of the role
# Role Configuration:
# This Role, named 'secret-reader', grants read-only access to Secrets within the 'bonita' namespace.
# It's a best practice to follow the principle of least privilege, granting only the necessary permissions to users or applications.
# This role ensures that applications or users with this role can only view (get, list, watch) Secrets, but not modify them, enhancing the security posture.
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]  # Permissions include getting, listing, and watching Secrets.